### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by haarp** [michaellass/ladspa-notch-harmonics#1]
Hi!

just wanted to say thank you!

I was struggling with standing waves in my room at 117Hz which resulted in really ugly droning effects when listening to music or movies. I've tried notch_iir_1894 first, but Pulseaudio seems to turn that plugin into a lowpass instead of a notch filter for some reason (???) Your plugin works perfectly. I didn't even need the harmonics, but fortunately they can be disabled.

Have a great day!

**Comment by michaellass** [comment]
Thanks a lot for the shout-out! I'm always surprised how quickly people find stuff released on github. Your use-case is quite interesting. Not exactly what I had in mind when writing the plugin. I'm glad it works for you and good to know that it works in this low frequency range as well! :slightly_smiling_face:
