### ISSUE TITLE
Using the filter with Pipewire

### ISSUE THREAD

**Issue by SantX27** [michaellass/ladspa-notch-harmonics#3]
Hi, thank you for developing this LASDPA filter, it has been really useful.
I have got it running on Pipewire 0.3.60, modifying a bit the istructions in [werman](https://github.com/werman/noise-suppression-for-voice)'s noise suppression:

- Create config directory: **~/.config/pipewire/pipewire.conf.d/**
- Create config for plugin: **~/.config/pipewire/pipewire.conf.d/99-input-notch-harmonics.conf**
- Paste configuration:
```
context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description =  "Notch Harmonics source"
        media.name =  "Notch Harmonics source"
        filter.graph = {
            nodes = [
                {
                    type = ladspa
                    name = notch_harmonics
                    plugin = /usr/local/lib/ladspa/notch_harmonics_5761.so
                    label = notch_harmonics
                    control = {
                        "Base frequency" = 1000
                        "Number of harmonics" = 12
                    }
                }
            ]
        }
        capture.props = {
            node.name =  "capture.notch_harmonics"
            node.passive = true
        }
        playback.props = {
            node.name =  "notch_harmonics"
            media.class = Audio/Source
        }
    }
}
]
```
- Restart PipeWire: **systemctl restart --user pipewire.service**
- Now you should be able to select **Notch Harmonics source** as input device

If I find the time, I could try to mix your notch harmonics with werman's noise suppression in one source, it just needs some modifications to the conf file...

**Comment by michaellass** [comment]
Hi. That's great, thanks a lot for posting! May I copy these instructions into the README file?

**Comment by SantX27** [comment]
Yeah absolutely! If I get around on doing the double filtering with rnnoise I will add another comment here.

**Comment by michaellass** [comment]
Thanks @SantX27! I added your description to the README.md and will close this issue for now. If the double filtering turns out useful, please add a comment so that we can revisit the description.

**Comment by jakoprd** [comment]
it read internal ALC1150 audio as input. How to set pipewire for external USB microphone?
```
wpctl status
PipeWire 'pipewire-0' [0.3.74, bb@xx, cookie:1504784592]
 └─ Clients:
        32. pipewire                            [0.3.74, bb@xx, pid:16124]
        33. WirePlumber                         [0.3.74, bb@xx, pid:16125]
        34. WirePlumber [export]                [0.3.74, bb@xx, pid:16125]
        68. wpctl                               [0.3.74, bb@xx, pid:23466]

Audio
 ├─ Devices:
 │      42. Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series] [alsa]
 │      43. Meteor condenser microphone         [alsa]
 │      44. Built-in Audio                      [alsa]
 │  
 ├─ Sinks:
 │      46. Meteor condenser microphone Analog Stereo [vol: 0.65]
 │  *   48. Built-in Audio Analog Stereo        [vol: 0.75]
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  *   36. Notch Harmonics source              [vol: 1.00]
 │      47. Meteor condenser microphone Analog Stereo [vol: 1.00]
 │      49. Built-in Audio Analog Stereo        [vol: 1.00]
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:
        35. capture.notch_harmonics                                     
             62. input_FL        < ALC1150 Analog:capture_FL	[paused]
             63. monitor_FL     
             64. input_FR        < ALC1150 Analog:capture_FR	[paused]
             65. monitor_FR     

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Settings
 └─ Default Configured Node Names:
         0. Audio/Sink    alsa_output.pci-0000_00_1b.0.analog-stereo
         1. Audio/Source  notch_harmonics
```

**Comment by jakoprd** [comment]
I found solution how to force plugin use external USB microphone intead mainboard internal audio. define target.object in capture.props part
```
        capture.props = {
            node.name =  "capture.notch_harmonics"
            node.passive = true
            target.object = "alsa_input.usb-Samson_Technologies_Samson_Meteor_Mic-00.analog-stereo"
        }
```
maybe this will help someone

**Comment by michaellass** [comment]
Thanks a lot @jakoprd for providing the solution! I will add that line with a comment to the README.

**Comment by jakoprd** [comment]
today i upgraded pipewire from version 1.6.2 to version 1.6.3 and pipewire crashed print strange error
`pipewire[39091]: failed to load plugin '/usr/local/lib/ladspa/notch_harmonics_5761.so' in '/usr/lib64/ladspa:/usr/lib/ladspa:/usr/lib': No such file or directory
`
have no idea what is wrong here. fillesystem permissions are ok.
so i try move plugin from /usr/local/lib/ladspa to directory /usr/lib/ladspa change plugin path in config 99-input-notch-harmonics.conf and everything starts working again. mabye it is archlinux specific bug only
